# Generated by Django 4.0.6 on 2022-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='time_added',
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
