# Generated by Django 4.0.6 on 2022-09-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_stock_time_added_alter_stock_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-updated']},
        ),
    ]
